trigger:
- main

pool: anjalipool

stages:

- stage: InstallAndInit
  displayName: InstallAndInit
  jobs:
  - job: InstallAndInit
    displayName: InstallAndInit Job
    steps:
    - task: TerraformInstaller@1
      displayName: Terraform Install
      inputs:
        terraformVersion: '1.13.1'
    
    - task: TerraformTask@5
      displayName: Terraform Init
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)\environment\dev'
        backendServiceArm: 'simplecred'
        backendAzureRmStorageAccountName: 'stg1234anji'
        backendAzureRmContainerName: 'tfstate'
        backendAzureRmKey: 'adv.tfstate'

- stage: InitAndPlan
  displayName: InitAndPlan
  jobs:
  - job: InitAndPlan
    displayName: InitAndPlan Job
    steps:
    - task: TerraformTask@5
      displayName: Terraform Init
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)\environment\dev'
        backendServiceArm: 'simplecred'
        backendAzureRmStorageAccountName: 'stg1234anji'
        backendAzureRmContainerName: 'tfstate'
        backendAzureRmKey: 'adv.tfstate'
    - task: TerraformTask@5
      displayName: Plan
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)\environment\dev'
        environmentServiceNameAzureRM: 'simplecred'


- stage: manaualvalidation
  displayName: manaualvalidation
  jobs:
  - job: manaualvalidation
    displayName: manaualvalidation Job
    pool: server
    steps:
    - task: ManualValidation@1
      displayName: Manual Validation
      inputs:
        notifyUsers: 'anji.vish12@gmail.com'
        approvers: 'anji.vish12@gmail.com'

- stage: security
  displayName: security
  jobs:
  - job: security
    displayName: security Job
    steps:
    - task: PowerShell@2
      displayName: tfsec
      inputs:
        targetType: 'inline'
        script: 'tfsec'
        workingDirectory: '$(System.DefaultWorkingDirectory)\environment\dev'

- stage: linting
  displayName: linting
  jobs:
  - job: linting
    displayName: linting
    steps:
    - task: PowerShell@2
      displayName: tflint
      inputs:
        targetType: 'inline'
        script: 'tflint'
        workingDirectory: '$(System.DefaultWorkingDirectory)\environment\dev'

- stage: Deploy
  displayName: Deploy
  jobs:
  - job: deploy
    displayName: deploy
    steps:
    - task: TerraformTask@5
      displayName: Terraform Init
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)\environment\dev'
        backendAzureRmStorageAccountName: 'stg1234anji'
        backendAzureRmContainerName: 'tfstate'
        backendAzureRmKey: 'adv.tfstate'
    - task: TerraformTask@5
      displayName: apply
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: '$(System.DefaultWorkingDirectory)\environment\dev'
        environmentServiceNameAzureRM: 'simplecred'